version: "3.9"

services:
  issue-tracker-database:
    image: postgres:15.1-alpine
    container_name: Issuey-DB
    restart: always
    environment:
        - POSTGRES_DB=issue-tracker
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"