version: "3.9"

services:
  issue-tracker-database:
    image: postgres:15.1-alpine
    container_name: Issuey-DB
    restart: always
    environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"