spring:
  application:
    name: issue-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/issue-tracker
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver