name: Unit tests with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OUR code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn -B test --file pom.xml -Dgroups="unit-tests"